style:
  background_color: "#000000"

camera_qualities:
  low:
    resolution: "854x480"
    frame_rate: 15
  medium:
    resolution: "1280x720"
    frame_rate: 30
  high:
    resolution: "1920x1080"
    frame_rate: 60
  ultra_high:
    resolution: "3840x2160"
    frame_rate: 60
  default_quality: "medium"